#!/bin/sh
VOLUME=$(amixer sget Master | awk -F"[][]" '/Left:/ {print $2}' | sed 's/.$//')
IS_ON=$(amixer sget Master | awk -F"[][]" '/Left:/ {print $4}')
if [ $VOLUME -gt 50 ]; then
	GLYPH=
elif [ $VOLUME -gt 0 ]; then
	GLYPH=
else
	GLYPH=
fi
if [ "$IS_ON" = "off" ]; then
	GLYPH=
fi
echo "<span font_desc=\"\">$GLYPH</span> $VOLUME%"
